[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'solmate/=lib/solmate/src/',
    'seaport/=lib/seaport/',
    'seaport-types/=lib/seaport/lib/seaport-types/',
    'seaport-core/=lib/seaport/lib/seaport-core/',
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config