# Simple workflow for deploying static content to GitHub Pages
name: Build Docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  FOUNDRY_PROFILE: ci

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Document
        run: forge doc --build 

      - uses: stefanzweifel/git-auto-commit-action@v4 
        with: 
            commit_message: "document"
            branch: "md-book"
            create_branch: true
            push_options: "--force"


