name: test

on:
  workflow_dispatch:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn

      - uses: onbjerg/foundry-toolchain@v1

      - name: lint
        run: forge fmt --check
  
      - name: test
        run: forge test --ffi -vvv

      - name: snapshot
        run: forge snapshot

